config/routes.rb
Bboard::Application.routes.draw do
  resources :categories

  devise_for :users
  resources :posts
  root to: "posts#index"
  get '/posts/categories/:category_id' => 'posts#categorysearch', as: :categorysearch

  

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :categories

	attr_accessible  :category_name, :no_of_items
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
    belongs_to :category
	attr_accessible :user_id, :title, :category_id, :description
	validates :user_id,  presence: true
	validates :title,  presence: true
	validates :description,  presence: true
	validates :category_id,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true
                        #   format: 
                         #   {
                         #   	 with: /a-zA-Z0-9_-/, 
                         #   	 message: 'Must be formatted correctly.'
                         #   }

  has_many :posts

  def full_name
  		first_name+" "+last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name,:last_name,:profile_name,:email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name,:last_name,:profile_name,:email, :password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  #respond_to :html, :xml, :json

  def index
    @categories = Category.all
   # respond_with(@categories)
  end

  def show
    #respond_with(@category)
  end

  def new
    @category = Category.new
   # respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Post was successfully created.' }
        format.json { render action: 'show', categories: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, categories: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_name, :no_of_items)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("id DESC") 
    @categories = Category.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @categories = Category.all
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @categories = Category.all
    respond_to do |format|
      if @post.save
        #identified_category_id = @post.category_id
        #category = Category.find(identified_category_id)
       # category.no_of_items = category.no_of_items.to_i + 1
        #category.save
       # @categories = Category.all
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
       # @categories = Category.all
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def categorysearch
    @posts = Post.find_all_by_category_id(params[:category_id])
    @categories = Category.all
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit( :title,  :category_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
	   case type
	   when :alert
	   	    "alert-error"
	   	when :notice
	   		"alert-success"
	   	else
	   		""
	   	end
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<br><br>
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :category_name %>
    <%= f.input :no_of_items %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>No of items</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= category.no_of_items %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>

<p>
  <strong>No of items:</strong>
  <%= @category.no_of_items %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
     <div class="navbar-inner">
           <div class="container">
              <a href="#" class="brand">
              	Symantec BB
              </a>

              <ul class="nav">
              	<li>
              		<%= link_to "All Posts",posts_path   %>
              	</li>
              </ul>
              <ul class="nav pull-right">
                <% if user_signed_in? %>
                  <li>
                      <%= link_to current_user.full_name, edit_user_registration_path %>
                  </li> 
                  <li>
                      <%= link_to "Log Out",destroy_user_session_path, method: :delete %>
                  </li> 
                  <% else %>
                   <li>
                      <%= link_to "Register", new_user_registration_path %>
                   </li> 
                    <li>
                      <%= link_to "Log in",new_user_session_path %>
                    </li> 
                 <% end %>   
              </ul>
           </div>
     </div>
</div>
<div class="container">
   

   <% flash.each do |type , message| %>


       <div class="alert <%= flash_class type %> ">
             <button class="close" data-dismiss="alert">x</button>
             <%=  message  %>
        </div>
   <% end %>
  <div class="row">
  <div class="span2">
    <br><br><br>
    <ul class="nav nav-list">
     
  <% if !@categories.nil? %>
    <li class="nav-header"> Categories </li>
      <% @categories.each do |category| %>
      <li>  <%= link_to "#{ category.category_name }(#{ Post.find_all_by_category_id(category.id).length })", categorysearch_url(category.id) %>
           </li>
       <% end %>
    <% end %>
</ul>
    
  </div>
  <div class="span10">   <%= yield %> </div>
  </div>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: {class: "form-horizontal"}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
    <%= f.input :title %>
   <!-- <%= f.input :category_id %>  -->
    <%= f.input :category_id,:collection => @categories,:label_method => :category_name,:value_method => :id ,:include_blank => false %>
  <!--  <%= f.collection_select :category_id, @categories, :id, :category_name, :prompt => "Select a category" %> -->
    <%= f.input :description %>
   <div class="form-actions">
    <%= f.button :submit  %>
   </div>
<% end %>

app/views/posts/edit.html.erb
<br><br><br>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<br>
<%= link_to 'New Ad Post', new_post_path, class: "btn btn-success" %>
<% if !current_user.nil? and current_user.profile_name == "admin"%>
    <%= link_to 'New category', new_category_path, class: "btn btn-success" %>
    <%= link_to 'List Categories', categories_path, class: "btn btn-success" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Title</th>
      <th>Posted Before</th>
      <th>Category</th>
     
       <th></th>
     
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <% if !post.user.nil? %>
            <%= post.user.first_name %>
          <% end %>
        </td>
        <td><%= post.title %></td>
        <td><%= time_ago_in_words(post.created_at) %></td>
        <td><%= post.category.category_name %></td>
        
        <td>
          <% if !current_user.nil?  %>
            <div class="meta">
                   <%= link_to 'Show', post %>
                   <% if ((!current_user.nil? and !post.user.nil?) and  (current_user.profile_name == post.user.profile_name or current_user.profile_name == "admin" )) %>
                       |  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                   <% end %>
            </div>
            <% end %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<br><br><br>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
   <%= @post.user.first_name %> 
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Dateposted:</strong>
  <%= @post.created_at %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.category_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<% if current_user.profile_name == "admin"  || @post.user.profile_name == current_user.profile_name%>

    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Destroy', edit_post_path(@post) %>
<% end %>

<%= link_to 'Back', posts_path %>